export interface ComponentData {
  title: string;
  description: string;
  href: string;
  icon: string;
  color: string;
  category?: string;
}

export const componentCategories = [
  { slug: "accordions", label: "Accordions" },
  { slug: "ai-ui", label: "AI UI" },
  { slug: "avatars", label: "Avatars" },
  { slug: "backgrounds", label: "Backgrounds" },
  { slug: "badges", label: "Badges" },
  { slug: "buttons", label: "Buttons" },
  { slug: "cards", label: "Cards" },
  { slug: "carousels", label: "Carousels" },
  { slug: "cursors", label: "Cursors" },
  { slug: "data-display", label: "Data Display" },
  { slug: "dropdowns", label: "Dropdowns" },
  { slug: "feedback", label: "Feedback" },
  { slug: "forms", label: "Forms" },
  { slug: "icons", label: "Icons" },
  { slug: "inputs", label: "Inputs" },
  { slug: "layout", label: "Layout" },
  { slug: "loaders", label: "Loaders" },
  { slug: "materials", label: "Materials" },
  { slug: "media", label: "Media" },
  { slug: "mockups", label: "Mockups" },
  { slug: "modals", label: "Modals" },
  { slug: "navigation", label: "Navigation" },
  { slug: "pagination", label: "Pagination" },
  { slug: "scroll", label: "Scroll" },
  { slug: "sections", label: "Sections" },
  { slug: "switches", label: "Switches" },
  { slug: "tabs", label: "Tabs" },
  { slug: "text-effects", label: "Text Effects" },
  { slug: "tooltips", label: "Tooltips" },
  { slug: "transitions", label: "Transitions" },
  { slug: "typography", label: "Typography" }
];

export const componentsDataFull: ComponentData[] = [
  {
    title: "3D Animated Switch",
    description: "Interactive 3D toggle switch with synchronized DOM and WebGL animations using React Three Fiber and React Spring",
    href: "/showcase/3d-animated-switch",
    icon: "ToggleLeft",
    color: "from-cyan-400 to-rose-500",
    category: "switches",
  },
  {
    title: "3D Card Effects",
    description: "CSS 3D perspective cards with hover animations",
    href: "/showcase/cards",
    icon: "Sparkles",
    color: "from-purple-500 to-pink-500",
    category: "cards",
  },
  {
    title: "Futuristic Login Form",
    description: "Cyberpunk-styled login form with animated glitch/noise effects on focus and hover",
    href: "/showcase/futuristic-login",
    icon: "Lock",
    color: "from-indigo-500 to-purple-600",
    category: "forms",
  },
  {
    title: "Animated Testimonials",
    description: "Beautiful testimonial carousel with 3D stacking",
    href: "/showcase/testimonials",
    icon: "MessageSquareQuote",
    color: "from-pink-500 to-rose-500",
    category: "carousels",
  },
  {
    title: "Animated Tooltip",
    description: "Interactive profile tooltips with elastic GSAP animations",
    href: "/showcase/animated-tooltip",
    icon: "Users",
    color: "from-emerald-500 to-sky-500",
    category: "tooltips",
  },
  {
    title: "Curved World",
    description: "3D spherical world distortion effect on scroll",
    href: "/showcase/curved-world",
    icon: "Globe",
    color: "from-cyan-500 to-blue-500",
    category: "scroll",
  },
  {
    title: "Curved World Scroll",
    description: "Advanced curved world with scroll-driven animations",
    href: "/showcase/curved-world-scroll",
    icon: "ScrollText",
    color: "from-blue-500 to-purple-500",
    category: "scroll",
  },
  {
    title: "Custom Cursor",
    description: "Animated custom cursor with trail effects",
    href: "/showcase/custom-cursor",
    icon: "MousePointer2",
    color: "from-pink-500 to-purple-500",
    category: "cursors",
  },
  {
    title: "Cyberpunk Data Slicer",
    description: "Jagged cyberpunk search glyph that glitches the screen and reveals a scrambled CRT search bar",
    href: "/showcase/cyberpunk-data-slicer",
    icon: "Zap",
    color: "from-cyan-500 via-fuchsia-500 to-red-500",
    category: "inputs",
  },
  {
    title: "DaisyUI Theme Stress Test",
    description: "Comprehensive React application to stress test and visualize all 33 built-in DaisyUI themes with dynamic theme switcher and component showcase",
    href: "/showcase/daisyui-theme-stress-test",
    icon: "Palette",
    color: "from-pink-500 via-purple-500 to-indigo-500",
    category: "layout",
  },
  {
    title: "Destructible Cookie Consent",
    description: "Users smash the modal into physics debris using Matter.js, Voronoi tessellation, and html2canvas",
    href: "/showcase/destructible-cookie-consent",
    icon: "Cookie",
    color: "from-orange-500 via-red-500 to-pink-500",
    category: "modals",
  },
  {
    title: "Drag Viewpager",
    description: "Gesture-based image carousel with smooth drag interactions and scale animations powered by React Spring",
    href: "/showcase/drag-viewpager",
    icon: "Swipe",
    color: "from-blue-400 to-purple-500",
    category: "carousels",
  },
  {
    title: "Direction-Aware Hover",
    description: "Card overlays that intelligently enter from the exact edge where mouse approached using Math.atan2() angle detection",
    href: "/showcase/direction-aware-hover",
    icon: "Compass",
    color: "from-purple-500 via-pink-500 to-rose-500",
    category: "cards",
  },
  {
    title: "Displacement Hover",
    description: "Awwwards-standard image hover with texture-driven warping using Three.js shaders and displacement maps",
    href: "/showcase/displacement-hover",
    icon: "ImageIcon",
    color: "from-purple-600 via-blue-500 to-indigo-600",
    category: "cards",
  },
  {
    title: "Dithering & Halftone",
    description: "Bayer matrix dithering on 3D objects for Game Boy Camera or magazine print look",
    href: "/showcase/dithering",
    icon: "Grid3X3",
    color: "from-green-500 via-cyan-500 to-blue-500",
    category: "materials",
  },
  {
    title: "Electric Border",
    description: "Animated electric glow border with SVG filters",
    href: "/showcase/electric-border",
    icon: "Zap",
    color: "from-yellow-500 to-orange-500",
    category: "materials",
  },
  {
    title: "Event Horizon Modal",
    description: "A WebGL-powered modal experience where the background website is distorted into a gravitational singularity using React Three Fiber and GLSL shaders",
    href: "/showcase/event-horizon-modal",
    icon: "Atom",
    color: "from-cyan-400 via-purple-500 to-pink-500",
    category: "modals",
  },
  {
    title: "Expanding Search",
    description: "Animated search bar that grows and reveals filters on focus",
    href: "/showcase/search",
    icon: "Search",
    color: "from-indigo-500 to-purple-500",
    category: "inputs",
  },
  {
    title: "Ferrofluid Magnetic Input",
    description: "Search input made of magnetic particles that snap into ferrofluid text and react to typing",
    href: "/showcase/ferrofluid-magnetic-input",
    icon: "Search",
    color: "from-cyan-400 to-emerald-400",
    category: "inputs",
  },
  {
    title: "Ferrofluid Typography",
    description: "Magnetic liquid text with spikes that follow your cursor using GPGPU simulations",
    href: "/showcase/ferrofluid-typography",
    icon: "Droplets",
    color: "from-blue-500 via-purple-600 to-pink-600",
    category: "text-effects",
  },
  {
    title: "Film Grain Overlay",
    description: "Subtle static grain texture using SVG feTurbulence that kills flat digital look for cinematic, retro feel",
    href: "/showcase/film-grain",
    icon: "Film",
    color: "from-gray-600 via-gray-500 to-gray-400",
    category: "materials",
  },
  {
    title: "Floating 3D Object Viewer",
    description: "Interactive 3D objects with spring physics—rotate with mouse and watch them elastically return to center",
    href: "/showcase/floating-object-viewer",
    icon: "Box",
    color: "from-cyan-400 via-purple-500 to-pink-500",
    category: "media",
  },
  {
    title: "Fluid Cursor",
    description: "Smooth spring-based cursor with trailing effects",
    href: "/showcase/fluid-cursor",
    icon: "MousePointer2",
    color: "from-cyan-500 to-blue-500",
    category: "cursors",
  },
  {
    title: "Fluid Morphing Action Bar",
    description: "Dynamic Island-style floating navigation that physically morphs its shape using spring physics to accommodate different content",
    href: "/showcase/fluid-morphing-action-bar",
    icon: "CircleDot",
    color: "from-purple-500 to-pink-500",
    category: "navigation",
  },
  {
    title: "Fluid Scroll Progress",
    description: "Liquid thermometer-style progress indicator that ripples, splashes, and bulges around section markers with surface tension physics",
    href: "/showcase/fluid-scroll-progress",
    icon: "Droplets",
    color: "from-cyan-400 via-blue-500 to-purple-500",
    category: "scroll",
  },
  {
    title: "Gaussian Splatting",
    description: "Photorealistic 3D rendering using real-world scans with hologram-like interaction",
    href: "/showcase/gaussian-splatting",
    icon: "Atom",
    color: "from-cyan-400 via-indigo-500 to-purple-600",
    category: "cards",
  },
  {
    title: "Glassmorphism Refraction",
    description: "Real-time refraction with FBO rendering that actually magnifies and distorts content",
    href: "/showcase/glassmorphism-refraction",
    icon: "Boxes",
    color: "from-cyan-400 via-blue-500 to-purple-500",
    category: "materials",
  },
  {
    title: "RGB / Cyberpunk Glitch",
    description: "Digital chaos with RGB channel splitting, horizontal slicing, and data corruption for cyberpunk aesthetic",
    href: "/showcase/glitch-effects",
    icon: "Zap",
    color: "from-cyan-500 via-purple-500 to-magenta-500",
    category: "transitions",
  },
  {
    title: "Global Stats",
    description: "Interactive 3D globe showing real-time data points",
    href: "/showcase/globe",
    icon: "Globe",
    color: "from-blue-600 to-indigo-600",
    category: "data-display",
  },
  {
    title: "Interactive Grid",
    description: "A grid of dots that react and pulsate as the mouse moves over them",
    href: "/showcase/grid",
    icon: "Layout",
    color: "from-gray-500 to-gray-800",
    category: "backgrounds",
  },
  {
    title: "Holographic Depth-Map Parallax",
    description: "Realistic depth-based parallax effect using static images and depth maps",
    href: "/showcase/holographic-depth-parallax",
    icon: "Eye",
    color: "from-cyan-500 via-blue-500 to-purple-500",
    category: "cards",
  },
  {
    title: "Holographic Glass Tabs",
    description: "Tab switching with sliding refractive glass pane using transmission materials, chromatic aberration, and physics-based tilting",
    href: "/showcase/holographic-glass-tabs",
    icon: "Boxes",
    color: "from-purple-500 via-pink-500 to-cyan-500",
    category: "tabs",
  },
  {
    title: "Kinetic Reveal Footer",
    description: "Massive footer fixed at bottom while page scrolls up curtain-style to reveal it, with huge typography reacting to scroll velocity",
    href: "/showcase/kinetic-reveal-footer",
    icon: "ArrowDown",
    color: "from-purple-600 via-indigo-600 to-blue-600",
    category: "sections",
  },
  {
    title: "Kinetic String Input",
    description: "Physics-based string where letters hang and fall with gravity",
    href: "/showcase/kinetic-string-input",
    icon: "Type",
    color: "from-purple-500 to-pink-500",
    category: "inputs",
  },
  {
    title: "Kinetic Typography",
    description: "Interactive text where letters are connected by elastic physics strings with chain reaction drag",
    href: "/showcase/kinetic-typography",
    icon: "Move",
    color: "from-purple-600 via-fuchsia-500 to-pink-500",
    category: "text-effects",
  },
  {
    title: "Lens Effect",
    description: "Magnifying glass lens effect with smooth zoom",
    href: "/showcase/lens",
    icon: "Eye",
    color: "from-indigo-500 to-purple-500",
    category: "materials",
  },
  {
    title: "Liquid Image Distortion",
    description: "Images that liquefy and ripple like water on hover with WebGL shaders",
    href: "/showcase/liquid-image",
    icon: "Droplets",
    color: "from-cyan-400 to-blue-500",
    category: "media",
  },
  {
    title: "Liquid Lens Search",
    description: "Orb-based liquid search that morphs into a glassmorphism bar",
    href: "/showcase/liquid-lens",
    icon: "Eye",
    color: "from-cyan-500 to-indigo-500",
    category: "inputs",
  },
  {
    title: "Liquid Morphing Navigation",
    description: "Navigation menu with mercury-like active state blob that morphs organically between items using SVG gooey effects",
    href: "/showcase/liquid-morphing-navigation",
    icon: "Menu",
    color: "from-purple-500 via-pink-500 to-red-500",
    category: "navigation",
  },
  {
    title: "Live Pulse News Feed",
    description: "Real-time breaking news feed with AI-generated headlines, UFO animations, and pulsing live indicator",
    href: "/showcase/live-pulse-news-feed",
    icon: "Activity",
    color: "from-emerald-500 via-cyan-500 to-blue-500",
    category: "data-display",
  },
  {
    title: "Infinite Marquee",
    description: "Seamlessly looping marquee for logos, text, or images",
    href: "/showcase/marquee",
    icon: "ArrowRightLeft",
    color: "from-yellow-400 to-orange-500",
    category: "carousels",
  },
  {
    title: "Magnetic Elements",
    description: "Tactile, physical 'pull' effect for buttons and objects",
    href: "/showcase/magnetic",
    icon: "MousePointer2",
    color: "from-amber-500 to-yellow-500",
    category: "buttons",
  },
  {
    title: "Magnetic Field Interactions",
    description: "Elements that behave like magnets, attracting and repelling each other",
    href: "/showcase/magnetic-field",
    icon: "Zap",
    color: "from-red-500 to-blue-500",
    category: "cursors",
  },
  {
    title: "Magnetic Black Hole Pagination",
    description: "Pagination numbers as gravity wells with orbiting ring that flies between pages using squash & stretch physics",
    href: "/showcase/magnetic-pagination",
    icon: "CircleDot",
    color: "from-cyan-400 via-purple-500 to-pink-500",
    category: "pagination",
  },
  {
    title: "Metaballs / Goop",
    description: "Organic liquid mercury blobs that snap together when close, using CSS blur+contrast or SVG filters",
    href: "/showcase/metaballs",
    icon: "Droplets",
    color: "from-purple-600 via-pink-500 to-purple-600",
    category: "materials",
  },
  {
    title: "Neural Network Visualizer",
    description: "Animated neural networks showing data flow and activations",
    href: "/showcase/neural-network",
    icon: "Cpu",
    color: "from-purple-400 to-pink-400",
    category: "backgrounds",
  },
  {
    title: "Neumorphic Card",
    description: "Soft UI design with realistic shadows and highlights",
    href: "/showcase/neumorphic",
    icon: "Layers",
    color: "from-gray-400 to-gray-200",
    category: "cards",
  },
  {
    title: "Particle Wave Interactions",
    description: "Interactive particle systems with wave-like mouse responses",
    href: "/showcase/wave-particles",
    icon: "Zap",
    color: "from-blue-400 to-purple-400",
    category: "backgrounds",
  },
  {
    title: "SVG Path Drawing",
    description: "Animated SVG path drawing with spring-based transitions",
    href: "/showcase/path-drawing",
    icon: "Pencil",
    color: "from-pink-500 to-cyan-500",
    category: "media",
  },
  {
    title: "Parallax Scroll",
    description: "Multi-layered parallax scrolling effect with space-themed graphics and interactive navigation",
    href: "/showcase/parallax-scroll",
    icon: "Layers",
    color: "from-indigo-500 via-purple-500 to-pink-500",
    category: "scroll",
  },
  {
    title: "Perspective Skew Toasts",
    description: "3D toast notifications that enter like hanging signs, tilting and swinging based on mouse movement with glossy sheen effects",
    href: "/showcase/perspective-toast",
    icon: "MessageSquareQuote",
    color: "from-purple-500 via-pink-500 to-cyan-500",
    category: "feedback",
  },
  {
    title: "Physics Gravity Sandbox",
    description: "UI elements that fall, stack, and bounce with realistic 2D physics",
    href: "/showcase/physics-sandbox",
    icon: "Box",
    color: "from-indigo-500 to-purple-500",
    category: "layout",
  },
  {
    title: "Pixelated Transition",
    description: "Retro-futuristic WebGL transitions that pixelate images with chromatic aberration for gaming/tech aesthetics",
    href: "/showcase/pixelated-transition",
    icon: "Boxes",
    color: "from-indigo-600 via-purple-500 to-pink-500",
    category: "transitions",
  },
  {
    title: "Portal Zoom Search",
    description: "Circular search node that expands into a wormhole, revealing results while the origin blurs away",
    href: "/showcase/portal-zoom-search",
    icon: "Search",
    color: "from-cyan-400 via-sky-500 to-indigo-500",
    category: "inputs",
  },
  {
    title: "Prismatic Dispersion Glass",
    description: "Glassmorphism with chromatic aberration and RGB channel separation effects",
    href: "/showcase/prismatic-glass",
    icon: "Diamond",
    color: "from-pink-400 via-purple-400 to-cyan-400",
    category: "materials",
  },
  {
    title: "Quantum Loading States",
    description: "Electron orbital animations with quantum physics-inspired loading spinners",
    href: "/showcase/quantum-loading",
    icon: "Atom",
    color: "from-cyan-400 to-blue-400",
    category: "loaders",
  },
  {
    title: "Pure SVG Loaders",
    description: "Collection of 10 lightweight loading animations built with pure SVG and CSS animations",
    href: "/showcase/svg-loaders",
    icon: "Loader2",
    color: "from-gray-400 via-gray-200 to-white",
    category: "loaders",
  },
  {
    title: "Radar Mini-Map TOC",
    description: "Cyberpunk table of contents visualized as an interactive radar display with hyperspace warp navigation",
    href: "/showcase/radar-minimap-toc",
    icon: "Radar",
    color: "from-cyan-400 via-purple-400 to-pink-400",
    category: "navigation",
  },
  {
    title: "Raymarching / SDF",
    description: "Pure mathematical rendering with infinite resolution—no polygons, just raymarching through SDF equations for liquid morphing shapes",
    href: "/showcase/raymarch-sdf",
    icon: "Infinity",
    color: "from-purple-500 via-pink-500 to-blue-500",
    category: "backgrounds",
  },
  {
    title: "Reaction-Diffusion Patterns",
    description: "Biological growth patterns like zebra stripes and coral that evolve in real-time",
    href: "/showcase/reaction-diffusion",
    icon: "Activity",
    color: "from-cyan-400 via-purple-400 to-pink-400",
    category: "backgrounds",
  },
  {
    title: "Retro CRT",
    description: "Old school monitor effect with scanlines and curvature",
    href: "/showcase/crt",
    icon: "Cpu",
    color: "from-green-600 to-green-900",
    category: "materials",
  },
  {
    title: "Reveal Text",
    description: "Text with hover image reveals and gradient effects",
    href: "/showcase/reveal-text",
    icon: "ImageIcon",
    color: "from-emerald-500 to-green-500",
    category: "text-effects",
  },
  {
    title: "Rutt-Etra Video Synthesis",
    description: "Retro 70s video art where brightness becomes 3D height in scanline topology",
    href: "/showcase/rutt-etra",
    icon: "Activity",
    color: "from-cyan-500 via-pink-500 to-purple-500",
    category: "media",
  },
  {
    title: "Image Sequence Scroll",
    description: "Apple-style 3D product rotation controlled strictly through scroll progress with canvas rendering",
    href: "/showcase/scroll-effects",
    icon: "ScrollText",
    color: "from-cyan-600 via-blue-500 to-purple-500",
    category: "scroll",
  },
  {
    title: "Scroll Text Flow",
    description: "Scroll-triggered animated text with floating badges",
    href: "/showcase/scroll-text-flow",
    icon: "ScrollText",
    color: "from-rose-500 to-pink-500",
    category: "text-effects",
  },
  {
    title: "Scratch-to-Reveal Card",
    description: "Interactive scratch cards using Canvas—drag to erase and reveal hidden prizes, coupons, or messages",
    href: "/showcase/scratch-card",
    icon: "Hand",
    color: "from-yellow-400 via-orange-500 to-pink-500",
    category: "cards",
  },
  {
    title: "Scrollytelling / Sticky Pinning",
    description: "Immersive narratives with sticky visuals that stay pinned while text scrolls alongside, triggering animations (Apple-style product pages)",
    href: "/showcase/scrollytelling",
    icon: "BookOpen",
    color: "from-purple-500 via-pink-500 to-blue-500",
    category: "scroll",
  },
  {
    title: "Semantic AI Command Center",
    description: "Command+K AI assistant with bio-luminescent glow, intent-aware borders, and streaming responses",
    href: "/showcase/ai-command-center",
    icon: "Zap",
    color: "from-emerald-400 to-sky-500",
    category: "modals",
  },
  {
    title: "Slit-Scan Accordion",
    description: "FAQ accordion with WebGL shader reveal—content materializes from infinitely stretched vertical lines",
    href: "/showcase/slit-scan-accordion",
    icon: "ChevronDown",
    color: "from-cyan-400 via-purple-500 to-pink-500",
    category: "accordions",
  },
  {
    title: "Soft Body Physics Grid",
    description: "Grid of image cards that behave like jelly blocks, squishing and deforming on collision using Matter.js",
    href: "/showcase/soft-body-physics-grid",
    icon: "Grid3x3",
    color: "from-purple-500 via-pink-500 to-red-500",
    category: "layout",
  },
  {
    title: "Soft Body UI (Jelly Physics)",
    description: "UI elements that squish, stretch, and deform like jelly with spring physics",
    href: "/showcase/soft-body-ui",
    icon: "Droplets",
    color: "from-cyan-400 via-blue-500 to-purple-500",
    category: "materials",
  },
  {
    title: "Spotlight Torch Reveal",
    description: "Flashlight effect that reveals hidden content as you move the mouse",
    href: "/showcase/spotlight-reveal",
    icon: "Wand2",
    color: "from-yellow-400 to-orange-500",
    category: "materials",
  },
  {
    title: "Spotlight Void Search",
    description: "Torch-style search overlay that dims the page and reveals categories under a spotlight",
    href: "/showcase/spotlight-void",
    icon: "Search",
    color: "from-slate-500 to-cyan-500",
    category: "inputs",
  },
  {
    title: "Sticky Stacking Cards",
    description: "Cards enter from the bottom and stack on top of each other, staying fixed until section ends",
    href: "/showcase/sticky-stacking-cards",
    icon: "Layers",
    color: "from-purple-600 to-blue-500",
    category: "cards",
  },
  {
    title: "Text Animations",
    description: "Dynamic text effects with Framer Motion",
    href: "/showcase/text-animations",
    icon: "Palette",
    color: "from-green-500 to-teal-500",
    category: "text-effects",
  },
  {
    title: "Text Scramble",
    description: "High-energy text transition with scrambling characters",
    href: "/showcase/text-scramble",
    icon: "Type",
    color: "from-indigo-400 to-blue-400",
    category: "text-effects",
  },
  {
    title: "Theme Dropdown",
    description: "Animated theme switcher with smooth transitions",
    href: "/showcase/theme-dropdown",
    icon: "Palette",
    color: "from-indigo-500 to-purple-500",
    category: "switches",
  },
  {
    title: "Time Warp Transitions",
    description: "Page transitions with time dilation effects, speed lines, and color shifts",
    href: "/showcase/time-warp",
    icon: "Zap",
    color: "from-cyan-400 via-purple-400 to-pink-400",
    category: "transitions",
  },
  {
    title: "TypeWriter Effect",
    description: "GSAP-powered typewriter with rotating text animation",
    href: "/showcase/typewriter",
    icon: "Type",
    color: "from-blue-500 to-green-500",
    category: "text-effects",
  },
  {
    title: "Animated Tree View",
    description: "Expandable tree structure with smooth spring-based animations for nested content",
    href: "/showcase/tree-view",
    icon: "TreeDeciduous",
    color: "from-green-400 via-emerald-500 to-teal-500",
    category: "accordions",
  },
  {
    title: "UI Components",
    description: "Basic building blocks - Buttons, Inputs, Cards, etc.",
    href: "/showcase/buttons",
    icon: "Layers",
    color: "from-blue-500 to-cyan-500",
    category: "layout",
  },
  {
    title: "Variable Font Interaction",
    description: "Typography that changes weight, width dynamically based on mouse proximity or scroll speed",
    href: "/showcase/variable-font",
    icon: "Type",
    color: "from-purple-600 via-pink-500 to-orange-500",
    category: "text-effects",
  },
  {
    title: "Velocity-Based Scroll Skew",
    description: "Content skews diagonally based on scroll speed for feeling of weight and momentum using Lenis smooth scroll",
    href: "/showcase/velocity-scroll-skew",
    icon: "Activity",
    color: "from-cyan-500 via-blue-500 to-purple-500",
    category: "scroll",
  },
  {
    title: "Video Text Masking",
    description: "Big, bold typography where the ink of the text is actually a playing video for high-impact heroes",
    href: "/showcase/video-text-masking",
    icon: "Play",
    color: "from-pink-600 via-rose-500 to-red-500",
    category: "text-effects",
  },
  {
    title: "Voxel Terrain",
    description: "Isometric 3D landscape made of cubes with Perlin noise and wave propagation effects",
    href: "/showcase/voxel-terrain",
    icon: "Boxes",
    color: "from-green-600 via-teal-500 to-cyan-500",
    category: "backgrounds",
  },
  {
    title: "Voxel Terrain Filter",
    description: "3D voxel landscape that transforms based on search keywords",
    href: "/showcase/voxel-terrain-filter",
    icon: "Boxes",
    color: "from-blue-500 to-cyan-500",
    category: "inputs",
  },
  {
    title: "Voronoi Cell Grid",
    description: "Interactive cellular structure with real-time Voronoi diagram and spring physics",
    href: "/showcase/voronoi-grid",
    icon: "Layout",
    color: "from-purple-500 to-pink-500",
    category: "backgrounds",
  },
  {
    title: "X-Ray Reveal Cursor",
    description: "Cursor acts as an X-Ray lens revealing wireframe schematic version underneath the polished UI",
    href: "/showcase/xray-reveal-cursor",
    icon: "Eye",
    color: "from-green-400 via-emerald-500 to-cyan-500",
    category: "cursors",
  },
].sort((a, b) => a.title.localeCompare(b.title));

// Icon name to import mapping
export const iconMap = {
  "Sparkles": "Sparkles",
  "Box": "Box",
  "MessageSquareQuote": "MessageSquareQuote",
  "Users": "Users",
  "Terminal": "Terminal",
  "ArrowRightLeft": "ArrowRightLeft",
  "ArrowDown": "ArrowDown",
  "Cookie": "Cookie",
  "Layers": "Layers",
  "Activity": "Activity",
  "Search": "Search",
  "Zap": "Zap",
  "ImageIcon": "ImageIcon",
  "Shirt": "Shirt",
  "Type": "Type",
  "Cloud": "Cloud",
  "Globe": "Globe",
  "ScrollText": "ScrollText",
  "Compass": "Compass",
  "Grid3X3": "Grid3X3",
  "Droplets": "Droplets",
  "Film": "Film",
  "MousePointer2": "MousePointer2",
  "Atom": "Atom",
  "Boxes": "Boxes",
  "Layout": "Layout",
  "Eye": "Eye",
  "Move": "Move",
  "Cpu": "Cpu",
  "Pencil": "Pencil",
  "Diamond": "Diamond",
  "Infinity": "Infinity",
  "Radar": "Radar",
  "BookOpen": "BookOpen",
  "Palette": "Palette",
  "Wand2": "Wand2",
  "Play": "Play",
  "Flame": "Flame",
  "Grid3x3": "Grid3x3",
  "CircleDot": "CircleDot",
  "Menu": "Menu",
} as const;
