export interface ComponentData {
  title: string;
  description: string;
  href: string;
  category: string;
  icon: string;
  color: string;
}

export const componentsDataFull: ComponentData[] = [
  {
    title: "3D Card Effects",
    description: "CSS 3D perspective cards with hover animations",
    href: "/showcase/cards",
    category: "3d",
    icon: "Sparkles",
    color: "from-purple-500 to-pink-500",
  },
  {
    title: "3D Flip-Card Omnibar",
    description: "Isometric prism search bar that flips to reveal input and stacks results in Z-depth",
    href: "/showcase/3d-flip-omnibar",
    category: "search",
    icon: "Box",
    color: "from-sky-500 to-indigo-500",
  },
  {
    title: "Animated Testimonials",
    description: "Beautiful testimonial carousel with 3D stacking",
    href: "/showcase/testimonials",
    category: "animation",
    icon: "MessageSquareQuote",
    color: "from-pink-500 to-rose-500",
  },
  {
    title: "Animated Tooltip",
    description: "Interactive profile tooltips with elastic GSAP animations",
    href: "/showcase/animated-tooltip",
    category: "ui",
    icon: "Users",
    color: "from-emerald-500 to-sky-500",
  },
  {
    title: "ASCII Live Render",
    description: "Real-time video, image, or webcam feed rendered entirely out of text characters",
    href: "/showcase/ascii-render",
    category: "effects",
    icon: "Terminal",
    color: "from-green-500 to-emerald-500",
  },
  {
    title: "Barba.js Transitions",
    description: "Smooth page transitions with Barba.js for SPA-like experience",
    href: "/showcase/barba",
    category: "animation",
    icon: "ArrowRightLeft",
    color: "from-blue-600 to-purple-600",
  },
  {
    title: "Bento Grid",
    description: "Modern, versatile grid layout for feature showcases",
    href: "/showcase/bento-grid",
    category: "layout",
    icon: "Layers",
    color: "from-blue-600 to-indigo-600",
  },
  {
    title: "Boid Flocking Cursor",
    description: "Swarm of 50 intelligent agents following cursor using flocking algorithms: cohesion, alignment, and separation",
    href: "/showcase/boid-flocking-cursor",
    category: "interactive",
    icon: "MousePointer2",
    color: "from-cyan-400 via-blue-500 to-purple-500",
  },
  {
    title: "Bio-Luminescent Glow",
    description: "Organic pulsing glow effects mimicking deep-sea bioluminescence",
    href: "/showcase/bio-luminescent",
    category: "effects",
    icon: "Sparkles",
    color: "from-cyan-400 to-blue-400",
  },
  {
    title: "Bio-Organic Growth Loaders",
    description: "SVG-based organic shapes growing like vines using differential growth algorithms",
    href: "/showcase/bio-organic-growth-loader",
    category: "scientific",
    icon: "Activity",
    color: "from-emerald-400 to-cyan-400",
  },
  {
    title: "Breathing Variable Search",
    description: "Variable font weight reacts to typing speed with fluid cursor trail",
    href: "/showcase/breathing-variable-search",
    category: "search",
    icon: "Search",
    color: "from-purple-500 to-pink-500",
  },
  {
    title: "Chromatic Aberration",
    description: "Bad TV look with aggressive RGB channel splitting triggered by scroll or mouse speed",
    href: "/showcase/chromatic-aberration",
    category: "effects",
    icon: "Zap",
    color: "from-red-500 via-purple-500 to-cyan-500",
  },
  {
    title: "Chromatic Liquid Slider",
    description: "Image slider with liquid displacement and RGB channel separation based on drag velocity",
    href: "/showcase/chromatic-liquid-slider",
    category: "interactive",
    icon: "ImageIcon",
    color: "from-purple-500 via-pink-500 to-blue-500",
  },
  {
    title: "Cloth Simulation",
    description: "Realistic fabric physics using Verlet integration for draggable silk flags and curtains",
    href: "/showcase/cloth-simulation",
    category: "interactive",
    icon: "Shirt",
    color: "from-teal-600 via-cyan-500 to-blue-500",
  },
  {
    title: "Cloth-Simulated Typography",
    description: "Text that acts like a hanging flag or cloth, reacting to wind and cursor with physics",
    href: "/showcase/cloth-typography",
    category: "interactive",
    icon: "Type",
    color: "from-cyan-600 via-blue-500 to-purple-600",
  },
  {
    title: "Cloud Background",
    description: "Floating animated clouds with backdrop blur effects",
    href: "/showcase/cloud",
    category: "background",
    icon: "Cloud",
    color: "from-sky-400 to-blue-500",
  },
  {
    title: "Crystal Fractal Backgrounds",
    description: "Geometric crystal formations that grow and refract light dynamically",
    href: "/showcase/crystal-fractal",
    category: "scientific",
    icon: "Sparkles",
    color: "from-cyan-400 via-blue-400 to-purple-400",
  },
  {
    title: "Curved World",
    description: "3D spherical world distortion effect on scroll",
    href: "/showcase/curved-world",
    category: "3d",
    icon: "Globe",
    color: "from-cyan-500 to-blue-500",
  },
  {
    title: "Curved World Scroll",
    description: "Advanced curved world with scroll-driven animations",
    href: "/showcase/curved-world-scroll",
    category: "3d",
    icon: "ScrollText",
    color: "from-blue-500 to-purple-500",
  },
  {
    title: "Custom Cursor",
    description: "Animated custom cursor with trail effects",
    href: "/showcase/custom-cursor",
    category: "interactive",
    icon: "MousePointer2",
    color: "from-pink-500 to-purple-500",
  },
  {
    title: "Cyberpunk Data Slicer",
    description: "Jagged cyberpunk search glyph that glitches the screen and reveals a scrambled CRT search bar",
    href: "/showcase/cyberpunk-data-slicer",
    category: "search",
    icon: "Zap",
    color: "from-cyan-500 via-fuchsia-500 to-red-500",
  },
  {
    title: "Direction-Aware Hover",
    description: "Card overlays that intelligently enter from the exact edge where mouse approached using Math.atan2() angle detection",
    href: "/showcase/direction-aware-hover",
    category: "effects",
    icon: "Compass",
    color: "from-purple-500 via-pink-500 to-rose-500",
  },
  {
    title: "Displacement Hover",
    description: "Awwwards-standard image hover with texture-driven warping using Three.js shaders and displacement maps",
    href: "/showcase/displacement-hover",
    category: "effects",
    icon: "ImageIcon",
    color: "from-purple-600 via-blue-500 to-indigo-600",
  },
  {
    title: "Dithering & Halftone",
    description: "Bayer matrix dithering on 3D objects for Game Boy Camera or magazine print look",
    href: "/showcase/dithering",
    category: "effects",
    icon: "Grid3X3",
    color: "from-green-500 via-cyan-500 to-blue-500",
  },
  {
    title: "Electric Border",
    description: "Animated electric glow border with SVG filters",
    href: "/showcase/electric-border",
    category: "effects",
    icon: "Zap",
    color: "from-yellow-500 to-orange-500",
  },
  {
    title: "Expanding Search",
    description: "Animated search bar that grows and reveals filters on focus",
    href: "/showcase/search",
    category: "search",
    icon: "Search",
    color: "from-indigo-500 to-purple-500",
  },
  {
    title: "Ferrofluid Magnetic Input",
    description: "Search input made of magnetic particles that snap into ferrofluid text and react to typing",
    href: "/showcase/ferrofluid-magnetic-input",
    category: "search",
    icon: "Search",
    color: "from-cyan-400 to-emerald-400",
  },
  {
    title: "Ferrofluid Typography",
    description: "Magnetic liquid text with spikes that follow your cursor using GPGPU simulations",
    href: "/showcase/ferrofluid-typography",
    category: "text",
    icon: "Droplets",
    color: "from-blue-500 via-purple-600 to-pink-600",
  },
  {
    title: "Film Grain Overlay",
    description: "Subtle static grain texture using SVG feTurbulence that kills flat digital look for cinematic, retro feel",
    href: "/showcase/film-grain",
    category: "effects",
    icon: "Film",
    color: "from-gray-600 via-gray-500 to-gray-400",
  },
  {
    title: "Fluid Cursor",
    description: "Smooth spring-based cursor with trailing effects",
    href: "/showcase/fluid-cursor",
    category: "interactive",
    icon: "MousePointer2",
    color: "from-cyan-500 to-blue-500",
  },
  {
    title: "Gaussian Splatting",
    description: "Photorealistic 3D rendering using real-world scans with hologram-like interaction",
    href: "/showcase/gaussian-splatting",
    category: "3d",
    icon: "Atom",
    color: "from-cyan-400 via-indigo-500 to-purple-600",
  },
  {
    title: "Glassmorphism Refraction",
    description: "Real-time refraction with FBO rendering that actually magnifies and distorts content",
    href: "/showcase/glassmorphism-refraction",
    category: "3d",
    icon: "Boxes",
    color: "from-cyan-400 via-blue-500 to-purple-500",
  },
  {
    title: "RGB / Cyberpunk Glitch",
    description: "Digital chaos with RGB channel splitting, horizontal slicing, and data corruption for cyberpunk aesthetic",
    href: "/showcase/glitch-effects",
    category: "effects",
    icon: "Zap",
    color: "from-cyan-500 via-purple-500 to-magenta-500",
  },
  {
    title: "Global Stats",
    description: "Interactive 3D globe showing real-time data points",
    href: "/showcase/globe",
    category: "3d",
    icon: "Globe",
    color: "from-blue-600 to-indigo-600",
  },
  {
    title: "Interactive Grid",
    description: "A grid of dots that react and pulsate as the mouse moves over them",
    href: "/showcase/grid",
    category: "interactive",
    icon: "Layout",
    color: "from-gray-500 to-gray-800",
  },
  {
    title: "Holographic Depth-Map Parallax",
    description: "Realistic depth-based parallax effect using static images and depth maps",
    href: "/showcase/holographic-depth-parallax",
    category: "3d",
    icon: "Eye",
    color: "from-cyan-500 via-blue-500 to-purple-500",
  },
  {
    title: "Kinetic String Input",
    description: "Physics-based string where letters hang and fall with gravity",
    href: "/showcase/kinetic-string-input",
    category: "interactive",
    icon: "Type",
    color: "from-purple-500 to-pink-500",
  },
  {
    title: "Kinetic Typography",
    description: "Interactive text where letters are connected by elastic physics strings with chain reaction drag",
    href: "/showcase/kinetic-typography",
    category: "interactive",
    icon: "Move",
    color: "from-purple-600 via-fuchsia-500 to-pink-500",
  },
  {
    title: "Lens Effect",
    description: "Magnifying glass lens effect with smooth zoom",
    href: "/showcase/lens",
    category: "interactive",
    icon: "Eye",
    color: "from-indigo-500 to-purple-500",
  },
  {
    title: "Liquid Image Distortion",
    description: "Images that liquefy and ripple like water on hover with WebGL shaders",
    href: "/showcase/liquid-image",
    category: "interactive",
    icon: "Droplets",
    color: "from-cyan-400 to-blue-500",
  },
  {
    title: "Liquid Lens Search",
    description: "Orb-based liquid search that morphs into a glassmorphism bar",
    href: "/showcase/liquid-lens",
    category: "search",
    icon: "Eye",
    color: "from-cyan-500 to-indigo-500",
  },
  {
    title: "Infinite Marquee",
    description: "Seamlessly looping marquee for logos, text, or images",
    href: "/showcase/marquee",
    category: "animation",
    icon: "ArrowRightLeft",
    color: "from-yellow-400 to-orange-500",
  },
  {
    title: "Magnetic Elements",
    description: "Tactile, physical 'pull' effect for buttons and objects",
    href: "/showcase/magnetic",
    category: "interactive",
    icon: "MousePointer2",
    color: "from-amber-500 to-yellow-500",
  },
  {
    title: "Magnetic Field Interactions",
    description: "Elements that behave like magnets, attracting and repelling each other",
    href: "/showcase/magnetic-field",
    category: "scientific",
    icon: "Zap",
    color: "from-red-500 to-blue-500",
  },
  {
    title: "Metaballs / Goop",
    description: "Organic liquid mercury blobs that snap together when close, using CSS blur+contrast or SVG filters",
    href: "/showcase/metaballs",
    category: "effects",
    icon: "Droplets",
    color: "from-purple-600 via-pink-500 to-purple-600",
  },
  {
    title: "Neural Network Visualizer",
    description: "Animated neural networks showing data flow and activations",
    href: "/showcase/neural-network",
    category: "scientific",
    icon: "Cpu",
    color: "from-purple-400 to-pink-400",
  },
  {
    title: "Neumorphic Card",
    description: "Soft UI design with realistic shadows and highlights",
    href: "/showcase/neumorphic",
    category: "ui",
    icon: "Layers",
    color: "from-gray-300 to-gray-100",
  },
  {
    title: "Particle Wave Interactions",
    description: "Interactive particle systems with wave-like mouse responses",
    href: "/showcase/wave-particles",
    category: "interactive",
    icon: "Zap",
    color: "from-blue-400 to-purple-400",
  },
  {
    title: "SVG Path Drawing",
    description: "Animated SVG path drawing with spring-based transitions",
    href: "/showcase/path-drawing",
    category: "animation",
    icon: "Pencil",
    color: "from-pink-500 to-cyan-500",
  },
  {
    title: "Physics Gravity Sandbox",
    description: "UI elements that fall, stack, and bounce with realistic 2D physics",
    href: "/showcase/physics-sandbox",
    category: "interactive",
    icon: "Box",
    color: "from-indigo-500 to-purple-500",
  },
  {
    title: "Pixelated Transition",
    description: "Retro-futuristic WebGL transitions that pixelate images with chromatic aberration for gaming/tech aesthetics",
    href: "/showcase/pixelated-transition",
    category: "effects",
    icon: "Boxes",
    color: "from-indigo-600 via-purple-500 to-pink-500",
  },
  {
    title: "Portal Zoom Search",
    description: "Circular search node that expands into a wormhole, revealing results while the origin blurs away",
    href: "/showcase/portal-zoom-search",
    category: "search",
    icon: "Search",
    color: "from-cyan-400 via-sky-500 to-indigo-500",
  },
  {
    title: "Prismatic Dispersion Glass",
    description: "Glassmorphism with chromatic aberration and RGB channel separation effects",
    href: "/showcase/prismatic-glass",
    category: "effects",
    icon: "Diamond",
    color: "from-pink-400 via-purple-400 to-cyan-400",
  },
  {
    title: "Quantum Loading States",
    description: "Electron orbital animations with quantum physics-inspired loading spinners",
    href: "/showcase/quantum-loading",
    category: "scientific",
    icon: "Atom",
    color: "from-cyan-400 to-blue-400",
  },
  {
    title: "Raymarching / SDF",
    description: "Pure mathematical rendering with infinite resolution—no polygons, just raymarching through SDF equations for liquid morphing shapes",
    href: "/showcase/raymarch-sdf",
    category: "3d",
    icon: "Infinity",
    color: "from-purple-500 via-pink-500 to-blue-500",
  },
  {
    title: "Reaction-Diffusion Patterns",
    description: "Biological growth patterns like zebra stripes and coral that evolve in real-time",
    href: "/showcase/reaction-diffusion",
    category: "scientific",
    icon: "Activity",
    color: "from-cyan-400 via-purple-400 to-pink-400",
  },
  {
    title: "Retro CRT",
    description: "Old school monitor effect with scanlines and curvature",
    href: "/showcase/crt",
    category: "effects",
    icon: "Cpu",
    color: "from-green-600 to-green-900",
  },
  {
    title: "Reveal Text",
    description: "Text with hover image reveals and gradient effects",
    href: "/showcase/reveal-text",
    category: "animation",
    icon: "ImageIcon",
    color: "from-emerald-500 to-green-500",
  },
  {
    title: "Rutt-Etra Video Synthesis",
    description: "Retro 70s video art where brightness becomes 3D height in scanline topology",
    href: "/showcase/rutt-etra",
    category: "3d",
    icon: "Activity",
    color: "from-cyan-500 via-pink-500 to-purple-500",
  },
  {
    title: "Image Sequence Scroll",
    description: "Apple-style 3D product rotation controlled strictly through scroll progress with canvas rendering",
    href: "/showcase/scroll-effects",
    category: "interactive",
    icon: "ScrollText",
    color: "from-cyan-600 via-blue-500 to-purple-500",
  },
  {
    title: "Scroll Text Flow",
    description: "Scroll-triggered animated text with floating badges",
    href: "/showcase/scroll-text-flow",
    category: "animation",
    icon: "ScrollText",
    color: "from-rose-500 to-pink-500",
  },
  {
    title: "Scrollytelling / Sticky Pinning",
    description: "Immersive narratives with sticky visuals that stay pinned while text scrolls alongside, triggering animations (Apple-style product pages)",
    href: "/showcase/scrollytelling",
    category: "animation",
    icon: "BookOpen",
    color: "from-purple-500 via-pink-500 to-blue-500",
  },
  {
    title: "Semantic AI Command Center",
    description: "Command+K AI assistant with bio-luminescent glow, intent-aware borders, and streaming responses",
    href: "/showcase/ai-command-center",
    category: "search",
    icon: "Zap",
    color: "from-emerald-400 to-sky-500",
  },
  {
    title: "Soft Body UI (Jelly Physics)",
    description: "UI elements that squish, stretch, and deform like jelly with spring physics",
    href: "/showcase/soft-body-ui",
    category: "interactive",
    icon: "Droplets",
    color: "from-cyan-400 via-blue-500 to-purple-500",
  },
  {
    title: "Spotlight Torch Reveal",
    description: "Flashlight effect that reveals hidden content as you move the mouse",
    href: "/showcase/spotlight-reveal",
    category: "interactive",
    icon: "Wand2",
    color: "from-yellow-400 to-orange-500",
  },
  {
    title: "Spotlight Void Search",
    description: "Torch-style search overlay that dims the page and reveals categories under a spotlight",
    href: "/showcase/spotlight-void",
    category: "search",
    icon: "Search",
    color: "from-slate-500 to-cyan-500",
  },
  {
    title: "Sticky Stacking Cards",
    description: "Cards enter from the bottom and stack on top of each other, staying fixed until section ends",
    href: "/showcase/sticky-stacking-cards",
    category: "interactive",
    icon: "Layers",
    color: "from-purple-600 via-pink-500 to-orange-500",
  },
  {
    title: "Text Animations",
    description: "Dynamic text effects with Framer Motion",
    href: "/showcase/text-animations",
    category: "animation",
    icon: "Palette",
    color: "from-green-500 to-teal-500",
  },
  {
    title: "Text Scramble",
    description: "High-energy text transition with scrambling characters",
    href: "/showcase/text-scramble",
    category: "animation",
    icon: "Type",
    color: "from-indigo-400 to-blue-400",
  },
  {
    title: "Theme Dropdown",
    description: "Animated theme switcher with smooth transitions",
    href: "/showcase/theme-dropdown",
    category: "ui",
    icon: "Palette",
    color: "from-indigo-500 to-purple-500",
  },
  {
    title: "Time Warp Transitions",
    description: "Page transitions with time dilation effects, speed lines, and color shifts",
    href: "/showcase/time-warp",
    category: "animation",
    icon: "Zap",
    color: "from-cyan-400 via-purple-400 to-pink-400",
  },
  {
    title: "TypeWriter Effect",
    description: "GSAP-powered typewriter with rotating text animation",
    href: "/showcase/typewriter",
    category: "animation",
    icon: "Type",
    color: "from-blue-500 to-green-500",
  },
  {
    title: "UI Components",
    description: "Basic building blocks - Buttons, Inputs, Cards, etc.",
    href: "/showcase/buttons",
    category: "ui",
    icon: "Layers",
    color: "from-blue-500 to-cyan-500",
  },
  {
    title: "Variable Font Interaction",
    description: "Typography that changes weight, width dynamically based on mouse proximity or scroll speed",
    href: "/showcase/variable-font",
    category: "interactive",
    icon: "Type",
    color: "from-purple-600 via-pink-500 to-orange-500",
  },
  {
    title: "Velocity-Based Scroll Skew",
    description: "Content skews diagonally based on scroll speed for feeling of weight and momentum using Lenis smooth scroll",
    href: "/showcase/velocity-scroll-skew",
    category: "effects",
    icon: "Activity",
    color: "from-cyan-500 via-blue-500 to-purple-500",
  },
  {
    title: "Video Text Masking",
    description: "Big, bold typography where the ink of the text is actually a playing video for high-impact heroes",
    href: "/showcase/video-text-masking",
    category: "effects",
    icon: "Play",
    color: "from-pink-600 via-rose-500 to-red-500",
  },
  {
    title: "Voxel Terrain",
    description: "Isometric 3D landscape made of cubes with Perlin noise and wave propagation effects",
    href: "/showcase/voxel-terrain",
    category: "3d",
    icon: "Boxes",
    color: "from-green-600 via-teal-500 to-cyan-500",
  },
  {
    title: "Voxel Terrain Filter",
    description: "3D voxel landscape that transforms based on search keywords",
    href: "/showcase/voxel-terrain-filter",
    category: "3d",
    icon: "Boxes",
    color: "from-blue-500 to-cyan-500",
  },
  {
    title: "Voronoi Cell Grid",
    description: "Interactive cellular structure with real-time Voronoi diagram and spring physics",
    href: "/showcase/voronoi-grid",
    category: "interactive",
    icon: "Layout",
    color: "from-purple-500 to-pink-500",
  },
].sort((a, b) => a.title.localeCompare(b.title));

// Icon name to import mapping
export const iconMap = {
  "Sparkles": "Sparkles",
  "Box": "Box",
  "MessageSquareQuote": "MessageSquareQuote",
  "Users": "Users",
  "Terminal": "Terminal",
  "ArrowRightLeft": "ArrowRightLeft",
  "Layers": "Layers",
  "Activity": "Activity",
  "Search": "Search",
  "Zap": "Zap",
  "ImageIcon": "ImageIcon",
  "Shirt": "Shirt",
  "Type": "Type",
  "Cloud": "Cloud",
  "Globe": "Globe",
  "ScrollText": "ScrollText",
  "Compass": "Compass",
  "Grid3X3": "Grid3X3",
  "Droplets": "Droplets",
  "Film": "Film",
  "MousePointer2": "MousePointer2",
  "Atom": "Atom",
  "Boxes": "Boxes",
  "Layout": "Layout",
  "Eye": "Eye",
  "Move": "Move",
  "Cpu": "Cpu",
  "Pencil": "Pencil",
  "Diamond": "Diamond",
  "Infinity": "Infinity",
  "BookOpen": "BookOpen",
  "Palette": "Palette",
  "Wand2": "Wand2",
  "Play": "Play",
} as const;
